// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bmm_lb
NumericVector bmm_lb(NumericVector A, NumericVector B, int Bn, int M, int K, int N);
RcppExport SEXP _dMod2_bmm_lb(SEXP ASEXP, SEXP BSEXP, SEXP BnSEXP, SEXP MSEXP, SEXP KSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type Bn(BnSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(bmm_lb(A, B, Bn, M, K, N));
    return rcpp_result_gen;
END_RCPP
}
// bmm_rb
NumericVector bmm_rb(NumericVector A, NumericVector B, int Bn, int M, int K, int N);
RcppExport SEXP _dMod2_bmm_rb(SEXP ASEXP, SEXP BSEXP, SEXP BnSEXP, SEXP MSEXP, SEXP KSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type Bn(BnSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(bmm_rb(A, B, Bn, M, K, N));
    return rcpp_result_gen;
END_RCPP
}
// bmm_bb
NumericVector bmm_bb(NumericVector A, NumericVector B, int Bn, int M, int K, int N);
RcppExport SEXP _dMod2_bmm_bb(SEXP ASEXP, SEXP BSEXP, SEXP BnSEXP, SEXP MSEXP, SEXP KSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type Bn(BnSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(bmm_bb(A, B, Bn, M, K, N));
    return rcpp_result_gen;
END_RCPP
}
// constraintL2_scalar_kernel
List constraintL2_scalar_kernel(NumericVector pars, Nullable<NumericMatrix> dP_opt, Nullable<NumericVector> dP2_opt, CharacterVector inner_par_names, Nullable<NumericVector> fixed_opt, CharacterVector mu_names, NumericVector mu, NumericVector sigma, CharacterVector sigma_pars, bool est, bool deriv);
RcppExport SEXP _dMod2_constraintL2_scalar_kernel(SEXP parsSEXP, SEXP dP_optSEXP, SEXP dP2_optSEXP, SEXP inner_par_namesSEXP, SEXP fixed_optSEXP, SEXP mu_namesSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP sigma_parsSEXP, SEXP estSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type dP_opt(dP_optSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type dP2_opt(dP2_optSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type inner_par_names(inner_par_namesSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type fixed_opt(fixed_optSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type mu_names(mu_namesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sigma_pars(sigma_parsSEXP);
    Rcpp::traits::input_parameter< bool >::type est(estSEXP);
    Rcpp::traits::input_parameter< bool >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(constraintL2_scalar_kernel(pars, dP_opt, dP2_opt, inner_par_names, fixed_opt, mu_names, mu, sigma, sigma_pars, est, deriv));
    return rcpp_result_gen;
END_RCPP
}
// datapointL2_kernel
List datapointL2_kernel(NumericVector pouter, Nullable<NumericVector> fixed_opt, NumericMatrix prdf, Nullable<NumericVector> dpred_attr_opt, Nullable<NumericVector> d2pred_attr_opt, std::string obs_name, double t, double sigma, std::string value_par, bool deriv);
RcppExport SEXP _dMod2_datapointL2_kernel(SEXP pouterSEXP, SEXP fixed_optSEXP, SEXP prdfSEXP, SEXP dpred_attr_optSEXP, SEXP d2pred_attr_optSEXP, SEXP obs_nameSEXP, SEXP tSEXP, SEXP sigmaSEXP, SEXP value_parSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pouter(pouterSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type fixed_opt(fixed_optSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type prdf(prdfSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type dpred_attr_opt(dpred_attr_optSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type d2pred_attr_opt(d2pred_attr_optSEXP);
    Rcpp::traits::input_parameter< std::string >::type obs_name(obs_nameSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< std::string >::type value_par(value_parSEXP);
    Rcpp::traits::input_parameter< bool >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(datapointL2_kernel(pouter, fixed_opt, prdf, dpred_attr_opt, d2pred_attr_opt, obs_name, t, sigma, value_par, deriv));
    return rcpp_result_gen;
END_RCPP
}
// constraintL2_mvn_kernel
List constraintL2_mvn_kernel(NumericVector pars, Nullable<NumericVector> fixed_opt, Nullable<NumericMatrix> dP_opt, Nullable<NumericVector> dP2_opt, CharacterVector inner_par_names, int K, int N, CharacterVector all_eta_names, NumericVector mu, NumericMatrix L_lower, bool include_chol_block);
RcppExport SEXP _dMod2_constraintL2_mvn_kernel(SEXP parsSEXP, SEXP fixed_optSEXP, SEXP dP_optSEXP, SEXP dP2_optSEXP, SEXP inner_par_namesSEXP, SEXP KSEXP, SEXP NSEXP, SEXP all_eta_namesSEXP, SEXP muSEXP, SEXP L_lowerSEXP, SEXP include_chol_blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type fixed_opt(fixed_optSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type dP_opt(dP_optSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type dP2_opt(dP2_optSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type inner_par_names(inner_par_namesSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type all_eta_names(all_eta_namesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type L_lower(L_lowerSEXP);
    Rcpp::traits::input_parameter< bool >::type include_chol_block(include_chol_blockSEXP);
    rcpp_result_gen = Rcpp::wrap(constraintL2_mvn_kernel(pars, fixed_opt, dP_opt, dP2_opt, inner_par_names, K, N, all_eta_names, mu, L_lower, include_chol_block));
    return rcpp_result_gen;
END_RCPP
}
// normL2_kernel
List normL2_kernel(List prediction, Nullable<List> err_list_opt, List meta_list, CharacterVector par_names_global, bool deriv2_requested, int threads, std::string bloq_mode);
RcppExport SEXP _dMod2_normL2_kernel(SEXP predictionSEXP, SEXP err_list_optSEXP, SEXP meta_listSEXP, SEXP par_names_globalSEXP, SEXP deriv2_requestedSEXP, SEXP threadsSEXP, SEXP bloq_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type prediction(predictionSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type err_list_opt(err_list_optSEXP);
    Rcpp::traits::input_parameter< List >::type meta_list(meta_listSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type par_names_global(par_names_globalSEXP);
    Rcpp::traits::input_parameter< bool >::type deriv2_requested(deriv2_requestedSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type bloq_mode(bloq_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(normL2_kernel(prediction, err_list_opt, meta_list, par_names_global, deriv2_requested, threads, bloq_mode));
    return rcpp_result_gen;
END_RCPP
}
// parvec_attach
SEXP parvec_attach(SEXP out, SEXP deriv, SEXP deriv2);
RcppExport SEXP _dMod2_parvec_attach(SEXP outSEXP, SEXP derivSEXP, SEXP deriv2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type out(outSEXP);
    Rcpp::traits::input_parameter< SEXP >::type deriv(derivSEXP);
    Rcpp::traits::input_parameter< SEXP >::type deriv2(deriv2SEXP);
    rcpp_result_gen = Rcpp::wrap(parvec_attach(out, deriv, deriv2));
    return rcpp_result_gen;
END_RCPP
}
// parvec_concat
SEXP parvec_concat(SEXP lst);
RcppExport SEXP _dMod2_parvec_concat(SEXP lstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lst(lstSEXP);
    rcpp_result_gen = Rcpp::wrap(parvec_concat(lst));
    return rcpp_result_gen;
END_RCPP
}
// prior_omega_kernel
List prior_omega_kernel(NumericVector omegaVec, IntegerMatrix cholLoc, LogicalVector isDiag, int K, double lkjEta, double scaleSD, int kindFlag);
RcppExport SEXP _dMod2_prior_omega_kernel(SEXP omegaVecSEXP, SEXP cholLocSEXP, SEXP isDiagSEXP, SEXP KSEXP, SEXP lkjEtaSEXP, SEXP scaleSDSEXP, SEXP kindFlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type omegaVec(omegaVecSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type cholLoc(cholLocSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type isDiag(isDiagSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type lkjEta(lkjEtaSEXP);
    Rcpp::traits::input_parameter< double >::type scaleSD(scaleSDSEXP);
    Rcpp::traits::input_parameter< int >::type kindFlag(kindFlagSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_omega_kernel(omegaVec, cholLoc, isDiag, K, lkjEta, scaleSD, kindFlag));
    return rcpp_result_gen;
END_RCPP
}
// residual_kernel_aloq
List residual_kernel_aloq(NumericVector pred, NumericMatrix dpred, Nullable<NumericVector> d2pred, NumericVector y_data, NumericVector sigma, Nullable<NumericMatrix> dsigma, Nullable<NumericVector> d2sigma, Nullable<NumericVector> lloq, List opts);
RcppExport SEXP _dMod2_residual_kernel_aloq(SEXP predSEXP, SEXP dpredSEXP, SEXP d2predSEXP, SEXP y_dataSEXP, SEXP sigmaSEXP, SEXP dsigmaSEXP, SEXP d2sigmaSEXP, SEXP lloqSEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dpred(dpredSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type d2pred(d2predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_data(y_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type dsigma(dsigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type d2sigma(d2sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type lloq(lloqSEXP);
    Rcpp::traits::input_parameter< List >::type opts(optsSEXP);
    rcpp_result_gen = Rcpp::wrap(residual_kernel_aloq(pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts));
    return rcpp_result_gen;
END_RCPP
}
// residual_kernel_bloq
List residual_kernel_bloq(NumericVector pred, NumericMatrix dpred, Nullable<NumericVector> d2pred, NumericVector y_data, NumericVector sigma, Nullable<NumericMatrix> dsigma, Nullable<NumericVector> d2sigma, Nullable<NumericVector> lloq, List opts);
RcppExport SEXP _dMod2_residual_kernel_bloq(SEXP predSEXP, SEXP dpredSEXP, SEXP d2predSEXP, SEXP y_dataSEXP, SEXP sigmaSEXP, SEXP dsigmaSEXP, SEXP d2sigmaSEXP, SEXP lloqSEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dpred(dpredSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type d2pred(d2predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_data(y_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type dsigma(dsigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type d2sigma(d2sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type lloq(lloqSEXP);
    Rcpp::traits::input_parameter< List >::type opts(optsSEXP);
    rcpp_result_gen = Rcpp::wrap(residual_kernel_bloq(pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts));
    return rcpp_result_gen;
END_RCPP
}
// trustL1_impl
List trustL1_impl(Function objfun, NumericVector parinit, NumericVector mu, NumericVector lambda, bool one_sided, double rinit, double rmax, Nullable<NumericVector> parscale, int iterlim, double ftol, double mtol, double gtol, double xtol, double rmin, double thetamax, std::string boundary, bool minimize, bool blather, Nullable<NumericVector> parupper, Nullable<NumericVector> parlower, bool printIter, Nullable<CharacterVector> traceFile);
RcppExport SEXP _dMod2_trustL1_impl(SEXP objfunSEXP, SEXP parinitSEXP, SEXP muSEXP, SEXP lambdaSEXP, SEXP one_sidedSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP parscaleSEXP, SEXP iterlimSEXP, SEXP ftolSEXP, SEXP mtolSEXP, SEXP gtolSEXP, SEXP xtolSEXP, SEXP rminSEXP, SEXP thetamaxSEXP, SEXP boundarySEXP, SEXP minimizeSEXP, SEXP blatherSEXP, SEXP parupperSEXP, SEXP parlowerSEXP, SEXP printIterSEXP, SEXP traceFileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type objfun(objfunSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type one_sided(one_sidedSEXP);
    Rcpp::traits::input_parameter< double >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parscale(parscaleSEXP);
    Rcpp::traits::input_parameter< int >::type iterlim(iterlimSEXP);
    Rcpp::traits::input_parameter< double >::type ftol(ftolSEXP);
    Rcpp::traits::input_parameter< double >::type mtol(mtolSEXP);
    Rcpp::traits::input_parameter< double >::type gtol(gtolSEXP);
    Rcpp::traits::input_parameter< double >::type xtol(xtolSEXP);
    Rcpp::traits::input_parameter< double >::type rmin(rminSEXP);
    Rcpp::traits::input_parameter< double >::type thetamax(thetamaxSEXP);
    Rcpp::traits::input_parameter< std::string >::type boundary(boundarySEXP);
    Rcpp::traits::input_parameter< bool >::type minimize(minimizeSEXP);
    Rcpp::traits::input_parameter< bool >::type blather(blatherSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parupper(parupperSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parlower(parlowerSEXP);
    Rcpp::traits::input_parameter< bool >::type printIter(printIterSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type traceFile(traceFileSEXP);
    rcpp_result_gen = Rcpp::wrap(trustL1_impl(objfun, parinit, mu, lambda, one_sided, rinit, rmax, parscale, iterlim, ftol, mtol, gtol, xtol, rmin, thetamax, boundary, minimize, blather, parupper, parlower, printIter, traceFile));
    return rcpp_result_gen;
END_RCPP
}
// trustL1_lockstep_impl
List trustL1_lockstep_impl(Function objfun_many, NumericMatrix parinit, NumericMatrix mu, NumericMatrix lambda, bool one_sided, double rinit, double rmax, Nullable<NumericVector> parscale, int iterlim, double ftol, double mtol, double gtol, double xtol, double rmin, double thetamax, bool minimize, bool blather, Nullable<NumericVector> parupper, Nullable<NumericVector> parlower);
RcppExport SEXP _dMod2_trustL1_lockstep_impl(SEXP objfun_manySEXP, SEXP parinitSEXP, SEXP muSEXP, SEXP lambdaSEXP, SEXP one_sidedSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP parscaleSEXP, SEXP iterlimSEXP, SEXP ftolSEXP, SEXP mtolSEXP, SEXP gtolSEXP, SEXP xtolSEXP, SEXP rminSEXP, SEXP thetamaxSEXP, SEXP minimizeSEXP, SEXP blatherSEXP, SEXP parupperSEXP, SEXP parlowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type objfun_many(objfun_manySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type one_sided(one_sidedSEXP);
    Rcpp::traits::input_parameter< double >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parscale(parscaleSEXP);
    Rcpp::traits::input_parameter< int >::type iterlim(iterlimSEXP);
    Rcpp::traits::input_parameter< double >::type ftol(ftolSEXP);
    Rcpp::traits::input_parameter< double >::type mtol(mtolSEXP);
    Rcpp::traits::input_parameter< double >::type gtol(gtolSEXP);
    Rcpp::traits::input_parameter< double >::type xtol(xtolSEXP);
    Rcpp::traits::input_parameter< double >::type rmin(rminSEXP);
    Rcpp::traits::input_parameter< double >::type thetamax(thetamaxSEXP);
    Rcpp::traits::input_parameter< bool >::type minimize(minimizeSEXP);
    Rcpp::traits::input_parameter< bool >::type blather(blatherSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parupper(parupperSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parlower(parlowerSEXP);
    rcpp_result_gen = Rcpp::wrap(trustL1_lockstep_impl(objfun_many, parinit, mu, lambda, one_sided, rinit, rmax, parscale, iterlim, ftol, mtol, gtol, xtol, rmin, thetamax, minimize, blather, parupper, parlower));
    return rcpp_result_gen;
END_RCPP
}
// trust_impl
List trust_impl(Function objfun, NumericVector parinit, double rinit, double rmax, Nullable<NumericVector> parscale, int iterlim, double ftol, double mtol, double gtol, double xtol, double rmin, double thetamax, std::string boundary, bool minimize, bool blather, Nullable<NumericVector> parupper, Nullable<NumericVector> parlower, bool printIter, Nullable<CharacterVector> traceFile);
RcppExport SEXP _dMod2_trust_impl(SEXP objfunSEXP, SEXP parinitSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP parscaleSEXP, SEXP iterlimSEXP, SEXP ftolSEXP, SEXP mtolSEXP, SEXP gtolSEXP, SEXP xtolSEXP, SEXP rminSEXP, SEXP thetamaxSEXP, SEXP boundarySEXP, SEXP minimizeSEXP, SEXP blatherSEXP, SEXP parupperSEXP, SEXP parlowerSEXP, SEXP printIterSEXP, SEXP traceFileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type objfun(objfunSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< double >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parscale(parscaleSEXP);
    Rcpp::traits::input_parameter< int >::type iterlim(iterlimSEXP);
    Rcpp::traits::input_parameter< double >::type ftol(ftolSEXP);
    Rcpp::traits::input_parameter< double >::type mtol(mtolSEXP);
    Rcpp::traits::input_parameter< double >::type gtol(gtolSEXP);
    Rcpp::traits::input_parameter< double >::type xtol(xtolSEXP);
    Rcpp::traits::input_parameter< double >::type rmin(rminSEXP);
    Rcpp::traits::input_parameter< double >::type thetamax(thetamaxSEXP);
    Rcpp::traits::input_parameter< std::string >::type boundary(boundarySEXP);
    Rcpp::traits::input_parameter< bool >::type minimize(minimizeSEXP);
    Rcpp::traits::input_parameter< bool >::type blather(blatherSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parupper(parupperSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parlower(parlowerSEXP);
    Rcpp::traits::input_parameter< bool >::type printIter(printIterSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type traceFile(traceFileSEXP);
    rcpp_result_gen = Rcpp::wrap(trust_impl(objfun, parinit, rinit, rmax, parscale, iterlim, ftol, mtol, gtol, xtol, rmin, thetamax, boundary, minimize, blather, parupper, parlower, printIter, traceFile));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dMod2_bmm_lb", (DL_FUNC) &_dMod2_bmm_lb, 6},
    {"_dMod2_bmm_rb", (DL_FUNC) &_dMod2_bmm_rb, 6},
    {"_dMod2_bmm_bb", (DL_FUNC) &_dMod2_bmm_bb, 6},
    {"_dMod2_constraintL2_scalar_kernel", (DL_FUNC) &_dMod2_constraintL2_scalar_kernel, 11},
    {"_dMod2_datapointL2_kernel", (DL_FUNC) &_dMod2_datapointL2_kernel, 10},
    {"_dMod2_constraintL2_mvn_kernel", (DL_FUNC) &_dMod2_constraintL2_mvn_kernel, 11},
    {"_dMod2_normL2_kernel", (DL_FUNC) &_dMod2_normL2_kernel, 7},
    {"_dMod2_parvec_attach", (DL_FUNC) &_dMod2_parvec_attach, 3},
    {"_dMod2_parvec_concat", (DL_FUNC) &_dMod2_parvec_concat, 1},
    {"_dMod2_prior_omega_kernel", (DL_FUNC) &_dMod2_prior_omega_kernel, 7},
    {"_dMod2_residual_kernel_aloq", (DL_FUNC) &_dMod2_residual_kernel_aloq, 9},
    {"_dMod2_residual_kernel_bloq", (DL_FUNC) &_dMod2_residual_kernel_bloq, 9},
    {"_dMod2_trustL1_impl", (DL_FUNC) &_dMod2_trustL1_impl, 22},
    {"_dMod2_trustL1_lockstep_impl", (DL_FUNC) &_dMod2_trustL1_lockstep_impl, 19},
    {"_dMod2_trust_impl", (DL_FUNC) &_dMod2_trust_impl, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_dMod2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
