# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bmm_lb <- function(A, B, Bn, M, K, N) {
    .Call(`_dMod2_bmm_lb`, A, B, Bn, M, K, N)
}

bmm_rb <- function(A, B, Bn, M, K, N) {
    .Call(`_dMod2_bmm_rb`, A, B, Bn, M, K, N)
}

bmm_bb <- function(A, B, Bn, M, K, N) {
    .Call(`_dMod2_bmm_bb`, A, B, Bn, M, K, N)
}

constraintL2_scalar_kernel <- function(pars, dP_opt, dP2_opt, inner_par_names, fixed_opt, mu_names, mu, sigma, sigma_pars, est, deriv = TRUE) {
    .Call(`_dMod2_constraintL2_scalar_kernel`, pars, dP_opt, dP2_opt, inner_par_names, fixed_opt, mu_names, mu, sigma, sigma_pars, est, deriv)
}

datapointL2_kernel <- function(pouter, fixed_opt, prdf, dpred_attr_opt, d2pred_attr_opt, obs_name, t, sigma, value_par, deriv = TRUE) {
    .Call(`_dMod2_datapointL2_kernel`, pouter, fixed_opt, prdf, dpred_attr_opt, d2pred_attr_opt, obs_name, t, sigma, value_par, deriv)
}

constraintL2_mvn_kernel <- function(pars, fixed_opt, dP_opt, dP2_opt, inner_par_names, K, N, all_eta_names, mu, L_lower, include_chol_block) {
    .Call(`_dMod2_constraintL2_mvn_kernel`, pars, fixed_opt, dP_opt, dP2_opt, inner_par_names, K, N, all_eta_names, mu, L_lower, include_chol_block)
}

focei_kernel_ping <- function(joint_cb, pars, fixed, conditions) {
    .Call(`_dMod2_focei_kernel_ping`, joint_cb, pars, fixed, conditions)
}

focei_eval_one_subject <- function(model_cb, err_cb, pars_full, fixed, meta_i, eta_block, Omega_inv, Omega_log_det) {
    .Call(`_dMod2_focei_eval_one_subject`, model_cb, err_cb, pars_full, fixed, meta_i, eta_block, Omega_inv, Omega_log_det)
}

focei_inner_trust <- function(model_cb, err_cb, pars_full, eta_warmstart, subject_meta, Omega_inv_mat, Omega_log_det, fixed, control, predict_cb = NULL) {
    .Call(`_dMod2_focei_inner_trust`, model_cb, err_cb, pars_full, eta_warmstart, subject_meta, Omega_inv_mat, Omega_log_det, fixed, control, predict_cb)
}

focei_outer_objfn <- function(model_cb, err_cb, joint_cb, outer_pars, eta_warmstart, subject_meta, Omega_inv_mat, Omega_log_det, fixed, inner_ctrl, correction_mode = "none", correction_cb_opt = NULL, predict_cb = NULL) {
    .Call(`_dMod2_focei_outer_objfn`, model_cb, err_cb, joint_cb, outer_pars, eta_warmstart, subject_meta, Omega_inv_mat, Omega_log_det, fixed, inner_ctrl, correction_mode, correction_cb_opt, predict_cb)
}

focei_run <- function(model_cb, err_cb, joint_cb, init, subject_meta, fixed, control, correction_mode = "none", correction_cb = NULL, predict_cb = NULL) {
    .Call(`_dMod2_focei_run`, model_cb, err_cb, joint_cb, init, subject_meta, fixed, control, correction_mode, correction_cb, predict_cb)
}

normalLaplaceCpp <- function(a, m, lambda) {
    .Call(`_dMod2_normalLaplaceCpp`, a, m, lambda)
}

clusterMarginalCpp <- function(H, m, lambda, sizes, B, L, zc, U, logw, z2, sgn) {
    .Call(`_dMod2_clusterMarginalCpp`, H, m, lambda, sizes, B, L, zc, U, logw, z2, sgn)
}

mcmcChainRun <- function(objfun, parinit, n, warmup, moveType, control, bounds, parscale_, dG_cb_opt) {
    .Call(`_dMod2_mcmc_chain_run`, objfun, parinit, n, warmup, moveType, control, bounds, parscale_, dG_cb_opt)
}

mcmcSmcReweight <- function(logL, logwPrev, betaOld, betaNew) {
    .Call(`_dMod2_mcmc_smc_reweight`, logL, logwPrev, betaOld, betaNew)
}

mcmcStratifiedResample <- function(weights) {
    .Call(`_dMod2_mcmc_stratified_resample`, weights)
}

mcmcResidualResample <- function(weights) {
    .Call(`_dMod2_mcmc_residual_resample`, weights)
}

mcmcMultinomialResample <- function(weights) {
    .Call(`_dMod2_mcmc_multinomial_resample`, weights)
}

normL2_kernel <- function(prediction, err_list_opt, meta_list, par_names_global, deriv2_requested, threads, bloq_mode = "M3") {
    .Call(`_dMod2_normL2_kernel`, prediction, err_list_opt, meta_list, par_names_global, deriv2_requested, threads, bloq_mode)
}

parvec_attach <- function(out, deriv, deriv2) {
    .Call(`_dMod2_parvec_attach`, out, deriv, deriv2)
}

parvec_concat <- function(lst) {
    .Call(`_dMod2_parvec_concat`, lst)
}

priorOmegaKernel <- function(omegaVec, cholLoc, isDiag, K, lkjEta, scaleSD, kindFlag) {
    .Call(`_dMod2_prior_omega_kernel`, omegaVec, cholLoc, isDiag, K, lkjEta, scaleSD, kindFlag)
}

#' @name sparseGridGH
#' @title Sparse-grid Gauss-Hermite quadrature nodes (Smolyak rule)
#' @description Builds the K-dimensional Smolyak sparse grid for physicists'
#'   Gauss-Hermite at depth `level`. Returns nodes `[B, K]` in z-space and
#'   signed weights (length `B`).
#' @param K Integer >= 1, problem dimension.
#' @param level Integer >= K, Smolyak depth (K+1..K+3 is the useful range).
#' @param derivMode Reserved for future Genz-Keister / adaptive refinement;
#'   currently ignored.
#' @return A list with `nodes` (B x K, batch-first), `weights` (length B,
#'   signed), and `K`, `level`.
#' @export
sparseGridGH <- function(K, level, derivMode = 0L) {
    .Call(`_dMod2_sparseGridGH`, K, level, derivMode)
}

residual_kernel_aloq <- function(pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts) {
    .Call(`_dMod2_residual_kernel_aloq`, pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts)
}

residual_kernel_bloq <- function(pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts) {
    .Call(`_dMod2_residual_kernel_bloq`, pred, dpred, d2pred, y_data, sigma, dsigma, d2sigma, lloq, opts)
}

smcLogSumExp <- function(x) {
    .Call(`_dMod2_smc_log_sum_exp`, x)
}

smcESS <- function(logw) {
    .Call(`_dMod2_smc_ess`, logw)
}

smcSystematicResample <- function(weights, u) {
    .Call(`_dMod2_smc_systematic_resample`, weights, u)
}

smcBetaBisect <- function(logL, logwPrev, betaOld, targetESS, tol = 1e-6, maxIter = 80L) {
    .Call(`_dMod2_smc_beta_bisect`, logL, logwPrev, betaOld, targetESS, tol, maxIter)
}

trustL1_impl <- function(objfun, parinit, mu, lambda, one_sided, rinit, rmax, parscale = NULL, iterlim = 100L, ftol = 1e-6, mtol = 1e-6, gtol = 1e-6, xtol = 0.0, rmin = 0.0, thetamax = 0.99995, boundary = "reflective", minimize = TRUE, blather = FALSE, parupper = NULL, parlower = NULL, printIter = FALSE, traceFile = NULL) {
    .Call(`_dMod2_trustL1_impl`, objfun, parinit, mu, lambda, one_sided, rinit, rmax, parscale, iterlim, ftol, mtol, gtol, xtol, rmin, thetamax, boundary, minimize, blather, parupper, parlower, printIter, traceFile)
}

trustL1_lockstep_impl <- function(objfun_many, parinit, mu, lambda, one_sided, rinit, rmax, parscale = NULL, iterlim = 100L, ftol = 1e-6, mtol = 1e-6, gtol = 1e-6, xtol = 0.0, rmin = 0.0, thetamax = 0.99995, minimize = TRUE, blather = FALSE, parupper = NULL, parlower = NULL) {
    .Call(`_dMod2_trustL1_lockstep_impl`, objfun_many, parinit, mu, lambda, one_sided, rinit, rmax, parscale, iterlim, ftol, mtol, gtol, xtol, rmin, thetamax, minimize, blather, parupper, parlower)
}

trust_impl <- function(objfun, parinit, rinit, rmax, parscale = NULL, iterlim = 100L, ftol = 1e-6, mtol = 1e-6, gtol = 1e-6, xtol = 0.0, rmin = 0.0, thetamax = 0.99995, boundary = "reflective", minimize = TRUE, blather = FALSE, parupper = NULL, parlower = NULL, printIter = FALSE, traceFile = NULL) {
    .Call(`_dMod2_trust_impl`, objfun, parinit, rinit, rmax, parscale, iterlim, ftol, mtol, gtol, xtol, rmin, thetamax, boundary, minimize, blather, parupper, parlower, printIter, traceFile)
}

